version: "3"
services:
  db:
    image: "postgres:12.2-alpine"
    ports:
      - "6000:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "smartteam"
      DATABASE_URL: postgres://postgres:123456@db:5432/smartteam
  web:
    build: .
    # command: ["./wait-for-it.sh", "db:5432", "--", "npm", "start"]
    volumes:
      - "./app:/src/app"
    ports:
      - "3000:3000"
    restart: always
    # environment:
    #   PORT: 3000
    #   DB_USERNAME: postgres
    #   DB_PASSWORD: 123456
    #   DB_DATABASE: smartteam
    #   DB_HOSTNAME: postgres
    links:
      - db
