version: "3"
services:
  db:
    image: "postgres:12.2-alpine"
    ports:
      - "6000:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "smartteam"
      # DATABASE_URL: postgres://postgres:123456@db:5432/smartteam
  web:
    build: .
    entrypoint: /entrypoint.sh
    # command: ["./wait-for-it.sh", "db:5432", "--", "/entrypoint.sh"]
    volumes:
      - "./app:/src/app"
    env_file:
      - ./app/.env
    ports:
      - "3000:3000"
    # This will make docker always run when restart the system
    # restart: always
    links:
      - db
