version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd app/ && npm install
            - run: cd app/ && cp ./.env.example ./.env
            - run: cd app/ && npm run ci
  deploy:
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$66f33cf7-914b-4782-ad7d-c4e6aef5aa3c@git.heroku.com/$smart-team-api.git master

workflows:
  build-and-test:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: master

# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master

# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/python:3.6.2-stretch-browsers
#         environment:
#           FLASK_CONFIG: testing
#           TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
#       - image: circleci/postgres:9.6.5-alpine-ram
#         environment:
#           POSTGRES_USER: ubuntu
#           POSTGRES_DB: circle_test
#           POSTGRES_PASSWORD: ""
#     steps:
#       - checkout
#       - restore_cache:
#           key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
#       - run:
#           name: Install Python deps in a venv
#           command: |
#             python3 -m venv venv
#             . venv/bin/activate
#             pip install -r requirements/dev.txt
#       - save_cache:
#           key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
#           paths:
#             - "venv"
#       - run:
#           command: |
#             . venv/bin/activate
#             python manage.py test
#       - store_artifacts:
#           path: test-reports/
#           destination: tr1
#       - store_test_results:
#           path: test-reports/
#   deploy:
#     steps:
#       - checkout
#       - run:
#           name: Deploy Master to Heroku
#           command: |
#             git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
