version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    # docker:
    #   - image: circleci/node:13.10.1
    steps:
      - checkout
      # - setup_remote_docker
      - node/with-cache:
          steps:
            - run: cd app/ && npm install
            - run: cd app/ && cp ./.env.example ./.env
            - run: cd app/ && npm start
            - run: cd app/ && npm test
            # - run: cd app/ && git add .

workflows:
  build-and-test:
    jobs:
      - build-and-test
