version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - setup_remote_docker
      - node/with-cache:
          steps:
            # - run: cd app/ && npm install
            - run: cd app/ && cp ./.env.example ./.env
            # - run: cd app/ && npm start
            # - run: sudo groupadd docker
            # - run: sudo usermod -aG docker root
            # - run: sudo service docker restart
            - run: sudo docker-compose up --build
workflows:
  build-and-test:
    jobs:
      - build-and-test
