version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd app/ && npm install
            - run: cd app/ && cp ./.env.example ./.env
            - run: cd app/ && npm run ci
  deploy:
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$66f33cf7-914b-4782-ad7d-c4e6aef5aa3c@git.heroku.com/$smart-team-api.git master

workflows:
  build-and-test:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
